# Generated by Django 2.1.5 on 2019-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pya',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
